modLoader="javafml"
loaderVersion="[35,)"
license="GPL-3.0-or-later"

[[mods]]
modId="space"
version="0.1.0"
displayName="S P A C E"
logoFile="space.png"
authors="Ian Rehwinkel, Sebastian Gerdon and Robin Gerdon"
description='''
Explore space!
'''

[[dependencies.space]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.11,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.space]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
